const words = [];

words["foods"] = [
    "Bread",
    "Rice",
    "Beans",
    "Meat",
    "Chicken",
    "Fish",
    "Egg",
    "Milk",
    "Cheese",
    "Butter",
    "Yogurt",
    "Fruit",
    "Vegetable",
    "Legume",
    "Cereal",
    "Salad",
    "Soup",
    "Pizza",
    "Hamburger",
    "Sandwich",
    "Pasta",
    "Lasagna",
    "Sushi",
    "Sashimi",
    "Temaki",
    "Yakisoba",
    "Tempura",
    "Ceviche",
    "Barbecue",
    "Beef Stroganoff",
    "Feijoada",
    "Moqueca",
    "Vatapá",
    "Acarajé",
    "Kibbeh",
    "Sfiha",
    "Pasty",
    "Coxinha",
    "Risoles",
    "Meat pie",
    "Cake",
    "Cookie",
    "Sweet",
    "Chocolate",
    "Ice cream",
    "Flan",
    "Mousse",
    "Gelatin",
    "Cheese",
    "Wine",
    "Beer",
    "Soda",
    "Juice",
    "Coffee",
    "Tea",
    "Water",
    "Spice",
    "Seasoning",
    "Sauce",
    "Olive oil",
    "Vinegar",
    "Salt",
    "Pepper",
    "Garlic",
    "Onion",
    "Tomato",
    "Potato",
    "Carrot",
    "Zucchini",
    "Broccoli",
    "Cauliflower",
    "Spinach",
    "Lettuce",
    "Arugula",
    "Watercress",
    "Basil",
    "Oregano",
    "Parsley",
    "Chives",
    "Mint",
    "Black pepper",
    "Nutmeg"
];

words["objects"] = [
    "pen",
    "pencil",
    "eraser",
    "notebook",
    "book",
    "cell phone",
    "charger",
    "headphone",
    "key",
    "wallet",
    "purse",
    "backpack",
    "umbrella",
    "glasses",
    "watch",
    "bracelet",
    "necklace",
    "earrings",
    "ring",
    "table",
    "chair",
    "sofa",
    "bed",
    "mattress",
    "pillow",
    "blanket",
    "sheet",
    "towel",
    "rug",
    "lamp",
    "nightstand lamp",
    "outlet",
    "light switch",
    "fan",
    "air conditioner",
    "heater",
    "refrigerator",
    "stove",
    "oven",
    "microwave",
    "dishwasher",
    "washing machine",
    "dryer",
    "iron",
    "vacuum cleaner",
    "broom",
    "dustpan",
    "trash",
    "dishes",
    "silverware",
    "pot",
    "frying pan",
    "cup",
    "plate",
    "cup",
    "spoon",
    "fork",
    "knife",
    "can opener",
    "potato peeler",
    "pizza cutter",
    "bottle opener",
    "kettle",
    "coffee maker",
    "orange juicer",
    "blender",
    "mixer",
    "toaster",
    "barbecue grill",
    "picnic",
    "toolbox",
    "hammer",
    "nail",
    "screw",
    "screwdriver",
    "wrench",
    "saw",
    "hammer",
    "level",
    "tape measure",
    "ladder",
    "car",
    "motorcycle"
];

words["general"] = [
    "computer",
    "internet",
    "technology",
    "world",
    "people",
    "life",
    "time",
    "love",
    "money",
    "happiness",
    "health",
    "family",
    "friends",
    "food",
    "music",
    "books",
    "movies",
    "games",
    "sports",
    "travel",
    "nature",
    "animals",
    "science",
    "history",
    "art",
    "culture",
    "government",
    "economy",
    "education",
    "weather",
    "climate",
    "environment",
    "space",
    "universe",
    "stars",
    "planets",
    "galaxies",
    "sun",
    "moon",
    "earth",
    "water",
    "air",
    "fire",
    "earth",
    "energy",
    "power",
    "light",
    "darkness",
    "good",
    "evil",
    "right",
    "wrong",
    "true",
    "false",
    "up",
    "down",
    "in",
    "out",
    "on",
    "off",
    "big",
    "small",
    "fast",
    "slow",
    "high",
    "low",
    "hot",
    "cold",
    "new",
    "old",
    "happy",
    "sad",
    "angry",
    "scared",
    "tired",
    "hungry",
    "thirsty",
    "beautiful",
    "ugly",
    "interesting",
    "boring",
    "easy",
    "difficult"
];

export default words;